version: '3.8'

services:
  enactai-remote:
    build:
      context: .
      dockerfile: Dockerfile.remote
    ports:
      - "8082:8082"
    environment:
      - CONGRESS_GOV_API_KEY=${CONGRESS_GOV_API_KEY}
      - GOVINFO_API_KEY=${GOVINFO_API_KEY}
      - ENACTAI_API_TOKEN=${ENACTAI_API_TOKEN:-}
      - PORT=8082
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; exit(0 if httpx.get('http://localhost:8082/health').status_code == 200 else 1)"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - enactai-network

  # Optional: Nginx reverse proxy for production-like setup
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - enactai-remote
    networks:
      - enactai-network
    profiles:
      - production

networks:
  enactai-network:
    driver: bridge